export const stories = [
  {
    id: '1',
    name: 'Your Story',
    avatar: 'https://randomuser.me/api/portraits/men/1.jpg ',
  },
  {
    id: '2',
    name: 'Alice',
    avatar: 'https://randomuser.me/api/portraits/women/2.jpg ',
  },
  {
    id: '3',
    name: 'Bob',
    avatar: 'https://randomuser.me/api/portraits/men/3.jpg ',
  },
  {
    id: '4',
    name: 'Charlie',
    avatar: 'https://randomuser.me/api/portraits/women/4.jpg ',
  },
  {
    id: '5',
    name: 'David',
    avatar: 'https://randomuser.me/api/portraits/men/5.jpg ',
  },
];

export const posts = [
  {
    id: '1',
    username: 'Alice',
    avatar: 'https://randomuser.me/api/portraits/women/2.jpg',
    type: 'image',
    content:
      'https://imgv3.fotor.com/images/slider-image/A-clear-close-up-photo-of-a-woman.jpg',
    caption: 'Beautiful sunset at the beach! 🌅',
    likes: 123,
    comments: 15,
    timestamp: '2h',
  },

  {
    id: '2',
    username: 'Bob',
    avatar: 'https://randomuser.me/api/portraits/men/3.jpg',
    type: 'video',
    content: 'https://www.w3schools.com/html/mov_bbb.mp4',
    caption: 'Hiking in the mountains! 🏔️',
    likes: 256,
    comments: 30,
    timestamp: '5h',
  },

  {
    id: '3',
    username: 'Charlie',
    avatar: 'https://randomuser.me/api/portraits/women/4.jpg',
    type: 'carousel',
    content: [
      'https://picsum.photos/id/1025/400/400',
      'https://picsum.photos/id/1026/400/400',
      'https://picsum.photos/id/1027/400/400',
    ],
    caption: 'Coffee time ☕️',
    likes: 98,
    comments: 12,
    timestamp: '1d',
  },

  {
    id: '4',
    username: 'Dave',
    avatar: 'https://randomuser.me/api/portraits/men/5.jpg',
    type: 'ad',
    content: 'https://picsum.photos/id/1028/400/400',
    caption: 'Check out our latest collection! #Sponsored',
    likes: 500,
    comments: 20,
    timestamp: '12h',
  },

  {
    id: '5',
    username: 'Eve',
    avatar: 'https://randomuser.me/api/portraits/women/6.jpg',
    type: 'image',
    content: 'https://picsum.photos/id/1030/400/400',
    caption: 'Exploring the city streets 🚶‍♀️',
    likes: 345,
    comments: 45,
    timestamp: '3h',
  },

  {
    id: '6',
    username: 'Frank',
    avatar: 'https://randomuser.me/api/portraits/men/7.jpg',
    type: 'video',
    content: 'https://www.w3schools.com/html/movie.mp4',
    caption: 'Cycling through the countryside 🚴‍♂️',
    likes: 198,
    comments: 25,
    timestamp: '8h',
  },

  {
    id: '7',
    username: 'Grace',
    avatar: 'https://randomuser.me/api/portraits/women/8.jpg',
    type: 'carousel',
    content: [
      'https://picsum.photos/id/1032/400/400',
      'https://picsum.photos/id/1033/400/400',
      'https://picsum.photos/id/1034/400/400',
    ],
    caption: 'Weekend getaway vibes 🏖️',
    likes: 78,
    comments: 10,
    timestamp: '2d',
  },

  {
    id: '8',
    username: 'Henry',
    avatar: 'https://randomuser.me/api/portraits/men/9.jpg',
    type: 'ad',
    content: 'https://picsum.photos/id/1035/400/400',
    caption: 'Upgrade your tech today! #Sponsored',
    likes: 678,
    comments: 50,
    timestamp: '18h',
  },

  {
    id: '9',
    username: 'Irene',
    avatar: 'https://randomuser.me/api/portraits/women/10.jpg',
    type: 'image',
    content: 'https://picsum.photos/id/1036/400/400',
    caption: 'Morning coffee ritual ☕',
    likes: 234,
    comments: 34,
    timestamp: '4h',
  },

  {
    id: '10',
    username: 'Jack',
    avatar: 'https://randomuser.me/api/portraits/men/11.jpg',
    type: 'video',
    content: 'https://www.w3schools.com/html/mov_bbb.mp4',
    caption: 'Skateboarding in the park 🛹',
    likes: 456,
    comments: 67,
    timestamp: '10h',
  },

  {
    id: '11',
    username: 'Karen',
    avatar: 'https://randomuser.me/api/portraits/women/12.jpg',
    type: 'carousel',
    content: [
      'https://picsum.photos/id/1037/400/400',
      'https://picsum.photos/id/1038/400/400',
      'https://picsum.photos/id/1039/400/400',
    ],
    caption: 'Art gallery visit 🎨',
    likes: 120,
    comments: 18,
    timestamp: '3d',
  },

  {
    id: '12',
    username: 'Leo',
    avatar: 'https://randomuser.me/api/portraits/men/13.jpg',
    type: 'ad',
    content: 'https://picsum.photos/id/1040/400/400',
    caption: 'New arrivals just dropped! #Sponsored',
    likes: 890,
    comments: 75,
    timestamp: '24h',
  },

  {
    id: '13',
    username: 'Mia',
    avatar: 'https://randomuser.me/api/portraits/women/14.jpg',
    type: 'image',
    content: 'https://picsum.photos/id/1041/400/400',
    caption: 'Lazy afternoon vibes 😌',
    likes: 150,
    comments: 22,
    timestamp: '6h',
  },

  {
    id: '14',
    username: 'Noah',
    avatar: 'https://randomuser.me/api/portraits/men/15.jpg',
    type: 'video',
    content: 'https://www.w3schools.com/html/movie.mp4',
    caption: 'City cycling adventure 🚴‍♂️',
    likes: 210,
    comments: 28,
    timestamp: '7h',
  },

  {
    id: '15',
    username: 'Olivia',
    avatar: 'https://randomuser.me/api/portraits/women/16.jpg',
    type: 'carousel',
    content: [
      'https://picsum.photos/id/1042/400/400',
      'https://picsum.photos/id/1043/400/400',
      'https://picsum.photos/id/1044/400/400',
    ],
    caption: 'Weekend brunch with friends 🥞',
    likes: 180,
    comments: 20,
    timestamp: '12h',
  },

  {
    id: '16',
    username: 'Paul',
    avatar: 'https://randomuser.me/api/portraits/men/17.jpg',
    type: 'ad',
    content: 'https://picsum.photos/id/1045/400/400',
    caption: 'Don’t miss our summer sale! #Sponsored',
    likes: 720,
    comments: 35,
    timestamp: '20h',
  },

  {
    id: '17',
    username: 'Quinn',
    avatar: 'https://randomuser.me/api/portraits/women/18.jpg',
    type: 'image',
    content: 'https://picsum.photos/id/1046/400/400',
    caption: 'Chasing dreams 🌟',
    likes: 135,
    comments: 19,
    timestamp: '3h',
  },

  {
    id: '18',
    username: 'Ryan',
    avatar: 'https://randomuser.me/api/portraits/men/19.jpg',
    type: 'video',
    content: 'https://www.w3schools.com/html/mov_bbb.mp4',
    caption: 'Surfing the waves 🌊',
    likes: 320,
    comments: 40,
    timestamp: '9h',
  },

  {
    id: '19',
    username: 'Sophia',
    avatar: 'https://randomuser.me/api/portraits/women/20.jpg',
    type: 'carousel',
    content: [
      'https://picsum.photos/id/1047/400/400',
      'https://picsum.photos/id/1048/400/400',
      'https://picsum.photos/id/1049/400/400',
    ],
    caption: 'Weekend vibes 😎',
    likes: 145,
    comments: 17,
    timestamp: '2d',
  },

  {
    id: '20',
    username: 'Tom',
    avatar: 'https://randomuser.me/api/portraits/men/21.jpg',
    type: 'ad',
    content: 'https://picsum.photos/id/1050/400/400',
    caption: 'Discover our new collection! #Sponsored',
    likes: 950,
    comments: 80,
    timestamp: '30h',
  },

  {
    id: '21',
    username: 'Uma',
    avatar: 'https://randomuser.me/api/portraits/women/22.jpg',
    type: 'image',
    content: 'https://picsum.photos/id/1051/400/400',
    caption: 'Lost in nature 🌳',
    likes: 165,
    comments: 26,
    timestamp: '4h',
  },

  {
    id: '22',
    username: 'Victor',
    avatar: 'https://randomuser.me/api/portraits/men/23.jpg',
    type: 'video',
    content: 'https://www.w3schools.com/html/movie.mp4',
    caption: 'Adrenaline rush! ⚡',
    likes: 275,
    comments: 33,
    timestamp: '6h',
  },

  {
    id: '23',
    username: 'Wendy',
    avatar: 'https://randomuser.me/api/portraits/women/24.jpg',
    type: 'carousel',
    content: [
      'https://picsum.photos/id/1052/400/400',
      'https://picsum.photos/id/1053/400/400',
      'https://picsum.photos/id/1054/400/400',
    ],
    caption: 'Artistic expressions 🎭',
    likes: 190,
    comments: 29,
    timestamp: '1d',
  },

  {
    id: '24',
    username: 'Xander',
    avatar: 'https://randomuser.me/api/portraits/men/25.jpg',
    type: 'ad',
    content: 'https://picsum.photos/id/1055/400/400',
    caption: 'Exclusive offers inside! #Sponsored',
    likes: 820,
    comments: 45,
    timestamp: '15h',
  },

  {
    id: '25',
    username: 'Yvonne',
    avatar: 'https://randomuser.me/api/portraits/women/26.jpg',
    type: 'image',
    content: 'https://picsum.photos/id/1056/400/400',
    caption: 'Morning walk 🌄',
    likes: 142,
    comments: 20,
    timestamp: '5h',
  },

  {
    id: '26',
    username: 'Zach',
    avatar: 'https://randomuser.me/api/portraits/men/27.jpg',
    type: 'video',
    content: 'https://www.w3schools.com/html/mov_bbb.mp4',
    caption: 'Skating downtown 🛹',
    likes: 305,
    comments: 38,
    timestamp: '7h',
  },

  {
    id: '27',
    username: 'Alice2',
    avatar: 'https://randomuser.me/api/portraits/women/28.jpg',
    type: 'carousel',
    content: [
      'https://picsum.photos/id/1057/400/400',
      'https://picsum.photos/id/1058/400/400',
      'https://picsum.photos/id/1059/400/400',
    ],
    caption: 'Nature stroll 🍃',
    likes: 110,
    comments: 14,
    timestamp: '8h',
  },

  {
    id: '28',
    username: 'Bob2',
    avatar: 'https://randomuser.me/api/portraits/men/29.jpg',
    type: 'ad',
    content: 'https://picsum.photos/id/1060/400/400',
    caption: 'Fashion sale alert! #Sponsored',
    likes: 760,
    comments: 52,
    timestamp: '20h',
  },

  {
    id: '29',
    username: 'Charlie2',
    avatar: 'https://randomuser.me/api/portraits/women/30.jpg',
    type: 'image',
    content: 'https://picsum.photos/id/1061/400/400',
    caption: 'City lights at night 🌃',
    likes: 210,
    comments: 27,
    timestamp: '6h',
  },

  {
    id: '30',
    username: 'Dave2',
    avatar: 'https://randomuser.me/api/portraits/men/31.jpg',
    type: 'video',
    content: 'https://www.w3schools.com/html/movie.mp4',
    caption: 'Evening run 🏃‍♂️',
    likes: 330,
    comments: 40,
    timestamp: '9h',
  },

  {
    id: '31',
    username: 'Eve2',
    avatar: 'https://randomuser.me/api/portraits/women/32.jpg',
    type: 'carousel',
    content: [
      'https://picsum.photos/id/1062/400/400',
      'https://picsum.photos/id/1063/400/400',
      'https://picsum.photos/id/1064/400/400',
    ],
    caption: 'Gallery stroll 🎨',
    likes: 135,
    comments: 18,
    timestamp: '1d',
  },

  {
    id: '32',
    username: 'Frank2',
    avatar: 'https://randomuser.me/api/portraits/men/33.jpg',
    type: 'ad',
    content: 'https://picsum.photos/id/1065/400/400',
    caption: 'Latest gadgets here! #Sponsored',
    likes: 880,
    comments: 60,
    timestamp: '22h',
  },

  {
    id: '33',
    username: 'Grace2',
    avatar: 'https://randomuser.me/api/portraits/women/34.jpg',
    type: 'image',
    content: 'https://picsum.photos/id/1066/400/400',
    caption: 'A peaceful moment ✨',
    likes: 175,
    comments: 21,
    timestamp: '4h',
  },

  {
    id: '34',
    username: 'Hannah2',
    avatar: 'https://randomuser.me/api/portraits/women/35.jpg',
    type: 'video',
    content: 'https://www.w3schools.com/html/mov_bbb.mp4',
    caption: 'Dancing in the rain 💃',
    likes: 290,
    comments: 35,
    timestamp: '8h',
  },

  {
    id: '35',
    username: 'Ian2',
    avatar: 'https://randomuser.me/api/portraits/men/36.jpg',
    type: 'carousel',
    content: [
      'https://picsum.photos/id/1067/400/400',
      'https://picsum.photos/id/1068/400/400',
      'https://picsum.photos/id/1069/400/400',
    ],
    caption: 'Adventure awaits 🌄',
    likes: 160,
    comments: 20,
    timestamp: '2d',
  },

  {
    id: '36',
    username: 'Julia2',
    avatar: 'https://randomuser.me/api/portraits/women/37.jpg',
    type: 'ad',
    content: 'https://picsum.photos/id/1070/400/400',
    caption: 'Special discount offer! #Sponsored',
    likes: 940,
    comments: 70,
    timestamp: '26h',
  },

  {
    id: '37',
    username: 'Kevin',
    avatar: 'https://randomuser.me/api/portraits/men/38.jpg',
    type: 'image',
    content: 'https://picsum.photos/id/1071/400/400',
    caption: 'Rainy day mood ☔',
    likes: 142,
    comments: 16,
    timestamp: '3h',
  },

  {
    id: '38',
    username: 'Laura',
    avatar: 'https://randomuser.me/api/portraits/women/39.jpg',
    type: 'video',
    content: 'https://www.w3schools.com/html/movie.mp4',
    caption: 'Morning workout routine 💪',
    likes: 310,
    comments: 42,
    timestamp: '7h',
  },

  {
    id: '39',
    username: 'Mike',
    avatar: 'https://randomuser.me/api/portraits/men/40.jpg',
    type: 'carousel',
    content: [
      'https://picsum.photos/id/1072/400/400',
      'https://picsum.photos/id/1073/400/400',
      'https://picsum.photos/id/1074/400/400',
    ],
    caption: 'Weekend picnic 🍉',
    likes: 155,
    comments: 19,
    timestamp: '1d',
  },

  {
    id: '40',
    username: 'Nina',
    avatar: 'https://randomuser.me/api/portraits/women/41.jpg',
    type: 'ad',
    content: 'https://picsum.photos/id/1075/400/400',
    caption: 'Buy one get one free! #Sponsored',
    likes: 860,
    comments: 55,
    timestamp: '20h',
  },

  {
    id: '41',
    username: 'Oliver',
    avatar: 'https://randomuser.me/api/portraits/men/42.jpg',
    type: 'image',
    content: 'https://picsum.photos/id/1076/400/400',
    caption: 'Cityscape at dusk 🌆',
    likes: 205,
    comments: 33,
    timestamp: '5h',
  },

  {
    id: '42',
    username: 'Paula',
    avatar: 'https://randomuser.me/api/portraits/women/43.jpg',
    type: 'video',
    content: 'https://www.w3schools.com/html/mov_bbb.mp4',
    caption: 'Fresh vibes and good music 🎶',
    likes: 275,
    comments: 39,
    timestamp: '8h',
  },

  {
    id: '43',
    username: 'Quentin',
    avatar: 'https://randomuser.me/api/portraits/men/44.jpg',
    type: 'carousel',
    content: [
      'https://picsum.photos/id/1077/400/400',
      'https://picsum.photos/id/1078/400/400',
      'https://picsum.photos/id/1079/400/400',
    ],
    caption: 'Travel diaries 🌍',
    likes: 190,
    comments: 22,
    timestamp: '2d',
  },

  {
    id: '44',
    username: 'Rachel',
    avatar: 'https://randomuser.me/api/portraits/women/45.jpg',
    type: 'ad',
    content: 'https://picsum.photos/id/1080/400/400',
    caption: 'Summer deals are here! #Sponsored',
    likes: 980,
    comments: 80,
    timestamp: '24h',
  },

  {
    id: '45',
    username: 'Sam',
    avatar: 'https://randomuser.me/api/portraits/men/46.jpg',
    type: 'image',
    content: 'https://picsum.photos/id/1081/400/400',
    caption: 'Nature at its best 🌲',
    likes: 175,
    comments: 21,
    timestamp: '4h',
  },

  {
    id: '46',
    username: 'Tina',
    avatar: 'https://randomuser.me/api/portraits/women/47.jpg',
    type: 'video',
    content: 'https://www.w3schools.com/html/movie.mp4',
    caption: 'Diving into adventures 🤿',
    likes: 285,
    comments: 36,
    timestamp: '9h',
  },

  {
    id: '47',
    username: 'Uma',
    avatar: 'https://randomuser.me/api/portraits/women/48.jpg',
    type: 'carousel',
    content: [
      'https://picsum.photos/id/1082/400/400',
      'https://picsum.photos/id/1083/400/400',
      'https://picsum.photos/id/1084/400/400',
    ],
    caption: 'Art in every corner 🎭',
    likes: 160,
    comments: 20,
    timestamp: '1d',
  },

  {
    id: '48',
    username: 'Victor',
    avatar: 'https://randomuser.me/api/portraits/men/49.jpg',
    type: 'ad',
    content: 'https://picsum.photos/id/1085/400/400',
    caption: 'Exclusive offers await! #Sponsored',
    likes: 920,
    comments: 65,
    timestamp: '19h',
  },

  {
    id: '49',
    username: 'Wendy',
    avatar: 'https://randomuser.me/api/portraits/women/50.jpg',
    type: 'image',
    content: 'https://picsum.photos/id/1086/400/400',
    caption: 'A perfect day at the park 🌳',
    likes: 210,
    comments: 30,
    timestamp: '3h',
  },

  {
    id: '50',
    username: 'Xavier',
    avatar: 'https://randomuser.me/api/portraits/men/51.jpg',
    type: 'video',
    content: 'https://www.w3schools.com/html/mov_bbb.mp4',
    caption: 'Urban exploration 🚶‍♂️',
    likes: 330,
    comments: 40,
    timestamp: '7h',
  },
];

export const sampleNotes = [
  {
    id: '1',
    name: 'Your Note',
    avatar: 'https://randomuser.me/api/portraits/women/1.jpg',
    note: 'Hello!',
  },
  {
    id: '2',
    name: 'Kate Shaw',
    avatar: 'https://randomuser.me/api/portraits/women/2.jpg',
    note: '😀 🍔',
  },
  {
    id: '3',
    name: 'Marcie Adams',
    avatar: 'https://randomuser.me/api/portraits/women/3.jpg',
    note: 'Busy day!',
  },
  {
    id: '4',
    name: 'John Doe',
    avatar: 'https://randomuser.me/api/portraits/men/4.jpg',
    note: 'Good vibes only!',
  },
  {
    id: '5',
    name: 'Chris Evans',
    avatar: 'https://randomuser.me/api/portraits/men/5.jpg',
    note: 'Need a vacation...',
  },
];

export const dummySearchResults = [
  {
    id: '1',
    name: 'Alice Johnson',
    profileUrl: 'https://randomuser.me/api/portraits/women/1.jpg',
  },
  {
    id: '2',
    name: 'Bob Smith',
    profileUrl: 'https://randomuser.me/api/portraits/men/2.jpg',
  },
  {
    id: '3',
    name: 'Charlie Brown',
    profileUrl: 'https://randomuser.me/api/portraits/men/3.jpg',
  },
  {
    id: '4',
    name: 'Diana Prince',
    profileUrl: 'https://randomuser.me/api/portraits/women/4.jpg',
  },
  {
    id: '5',
    name: 'Ethan Hunt',
    profileUrl: 'https://randomuser.me/api/portraits/men/5.jpg',
  },
];
